============================================================= test session starts =============================================================
platform linux -- Python 3.12.3, pytest-8.3.5, pluggy-1.5.0
rootdir: /home/lcs/Testing/Manhattan_Distance_Kata
collected 2 items

tests/test_manhattan_distance.py .F                                                                                                     [100%]

================================================================== FAILURES ===================================================================
___________________________________________________________ test_not_aligned_points ___________________________________________________________

    def test_not_aligned_points():

        p1 = Point(1,1)
        p2 = Point(3,3)
        p3 = Point(5,3)

        assert manhattanDistance(p1, p2) == 4
        assert manhattanDistance(p2, p3) == 2
>       assert manhattanDistance(p2, p1) == 4
E       assert 0 == 4
E        +  where 0 = manhattanDistance(<source.manhattan_distance.Point object at 0x7fbd46ffbb60>, <source.manhattan_distance.Point object at 0x7fbd46ffb2c0>)

tests/test_manhattan_distance.py:21: AssertionError
=========================================================== short test summary info ===========================================================
FAILED tests/test_manhattan_distance.py::test_not_aligned_points - assert 0 == 4
========================================================= 1 failed, 1 passed in 0.02s =========================================================