============================================================= test session starts =============================================================
platform linux -- Python 3.12.3, pytest-8.3.5, pluggy-1.5.0
rootdir: /home/lcs/Testing/Manhattan_Distance_Kata
collected 1 item

tests/test_manhattan_distance.py F                                                                                                      [100%]

================================================================== FAILURES ===================================================================
_____________________________________________________________ test_aligned_points _____________________________________________________________

    def test_aligned_points():
        p1 = Point(1,1)
        p2 = Point(1,3)
        p3 = Point(1,5)

>       assert manhattanDistance(p1, p2) == 2
E       assert 1 == 2
E        +  where 1 = manhattanDistance(<source.manhattan_distance.Point object at 0x7ffbc86dc890>, <source.manhattan_distance.Point object at 0x7ffbc875c140>)

tests/test_manhattan_distance.py:9: AssertionError
=========================================================== short test summary info ===========================================================
FAILED tests/test_manhattan_distance.py::test_aligned_points - assert 1 == 2
============================================================== 1 failed in 0.02s ==============================================================